import { migrateLegacyPlay, type LegacyPlay } from "./legacy";

export const originalStickThunder: LegacyPlay = {
  id: "play-8lkpvgj",
  name: "Stick — Thunder",
  cat: "Pass",
  tags: ["3rd down", "red zone"],
  notes:
    "Stick underneath, thunder outside — take the flat if the corner widens.",
  doc: {
    players: [
      {
        id: "ol0",
        x: 428,
        y: 448,
        symbol: "circle",
        label: "",
        sub: "",
        fill: "none",
        color: "k",
      },
      {
        id: "ol1",
        x: 464,
        y: 448,
        symbol: "circle",
        label: "",
        sub: "",
        fill: "none",
        color: "k",
      },
      {
        id: "ol2",
        x: 500,
        y: 448,
        symbol: "square",
        label: "",
        sub: "",
        fill: "none",
        color: "k",
      },
      {
        id: "ol3",
        x: 536,
        y: 448,
        symbol: "circle",
        label: "",
        sub: "",
        fill: "none",
        color: "k",
      },
      {
        id: "ol4",
        x: 572,
        y: 448,
        symbol: "circle",
        label: "",
        sub: "",
        fill: "none",
        color: "k",
      },
      {
        id: "q",
        x: 500,
        y: 478,
        symbol: "circle",
        label: "Q",
        sub: "",
        fill: "none",
        color: "k",
      },
      {
        id: "x",
        x: 316,
        y: 452,
        symbol: "circle",
        label: "X",
        sub: "FLAT",
        fill: "none",
        color: "k",
      },
      {
        id: "f",
        x: 281,
        y: 486,
        symbol: "circle",
        label: "F",
        sub: "STICK",
        fill: "none",
        color: "k",
      },
      {
        id: "h",
        x: 492,
        y: 560,
        symbol: "circle",
        label: "H",
        sub: "CHECK SLOW",
        fill: "none",
        color: "k",
      },
      {
        id: "y",
        x: 632,
        y: 452,
        symbol: "circle",
        label: "Y",
        sub: "OVER",
        fill: "none",
        color: "k",
      },
      {
        id: "z",
        x: 886,
        y: 452,
        symbol: "circle",
        label: "Z",
        sub: "THUNDER",
        fill: "none",
        color: "k",
      },
    ],
    routes: [
      {
        id: "rx",
        kind: "route",
        playerId: "x",
        branches: [],
        points: [
          { x: 316, y: 452 },
          { x: 308, y: 416 },
          { x: 126, y: 372 },
        ],
        lineStyle: "solid",
        endMarker: "arrow",
        color: "k",
      },
      {
        id: "rf",
        kind: "route",
        playerId: "f",
        branches: [],
        points: [
          { x: 281, y: 486 },
          { x: 300, y: 344 },
          { x: 238, y: 330 },
        ],
        lineStyle: "solid",
        endMarker: "arrow",
        color: "k",
      },
      {
        id: "ry",
        kind: "route",
        playerId: "y",
        branches: [],
        points: [
          { x: 632, y: 452 },
          { x: 616, y: 404 },
          { x: 524, y: 318 },
        ],
        lineStyle: "solid",
        endMarker: "dot",
        color: "k",
      },
      {
        id: "rh",
        kind: "route",
        playerId: "h",
        branches: [],
        points: [
          { x: 492, y: 560 },
          { x: 600, y: 514, tick: true },
          { x: 714, y: 406 },
        ],
        lineStyle: "solid",
        endMarker: "dot",
        color: "k",
      },
      {
        id: "rz",
        kind: "route",
        playerId: "z",
        branches: [
          {
            fromIdx: 1,
            points: [{ x: 912, y: 120 }],
            lineStyle: "dotted",
            endMarker: "arrow",
            color: "k",
          },
        ],
        points: [
          { x: 886, y: 452 },
          { x: 886, y: 296 },
        ],
        lineStyle: "solid",
        endMarker: "dot",
        color: "k",
      },
    ],
    labels: [
      {
        id: "l1",
        x: 96,
        y: 366,
        text: "1",
        color: "b",
        size: 13,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l2",
        x: 192,
        y: 352,
        text: "2-3 Yds",
        color: "k",
        size: 11,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l3",
        x: 222,
        y: 306,
        text: "2",
        color: "b",
        size: 13,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l4",
        x: 298,
        y: 300,
        text: "5 Yds",
        color: "k",
        size: 11,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l5",
        x: 498,
        y: 300,
        text: "3",
        color: "b",
        size: 13,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l6",
        x: 548,
        y: 278,
        text: "5 Yds",
        color: "k",
        size: 11,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l7",
        x: 728,
        y: 334,
        text: "2X2",
        color: "b",
        size: 11,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l8",
        x: 728,
        y: 352,
        text: "OUTLET",
        color: "b",
        size: 12,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l9",
        x: 728,
        y: 370,
        text: "3 Yds",
        color: "k",
        size: 11,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l10",
        x: 830,
        y: 286,
        text: "6 Yds",
        color: "k",
        size: 11,
        box: "none",
        boxColor: "y",
      },
      {
        id: "l11",
        x: 930,
        y: 238,
        text: "YES / NO",
        color: "r",
        size: 12,
        box: "outline",
        boxColor: "r",
      },
      {
        id: "l12",
        x: 886,
        y: 516,
        text: "MAX SPLIT +4",
        color: "k",
        size: 10,
        box: "fill",
        boxColor: "y",
      },
    ],
  },
};

export const stickThunderPlay = migrateLegacyPlay(originalStickThunder);
