import {
  highSchoolFieldProfile,
  playDocumentSchema,
  type PlayDocument,
} from "@chalk/domain";

const fixture = {
  schemaVersion: 2,
  id: "play_player_label_primitives",
  name: "Player and label primitive coverage",
  unit: "offense",
  playType: "Pass",
  tags: ["golden"],
  notes:
    "Exercises every original player symbol, fill, label role, and leader.",
  fieldProfile: highSchoolFieldProfile,
  players: [
    {
      id: "player-circle",
      unit: "offense",
      position: { lateralYards: -20, depthYards: 0 },
      symbol: "circle",
      label: "C",
      sublabel: "circle",
      fill: "none",
      color: "ink",
      role: "center",
      group: "offensive-line",
    },
    {
      id: "player-square",
      unit: "offense",
      position: { lateralYards: -12, depthYards: 0 },
      symbol: "square",
      label: "S",
      sublabel: "half",
      fill: "half",
      color: "blue",
    },
    {
      id: "player-oval",
      unit: "offense",
      position: { lateralYards: -4, depthYards: 0 },
      symbol: "oval",
      label: "B",
      sublabel: "solid",
      fill: "solid",
      color: "green",
    },
    {
      id: "player-triangle",
      unit: "special-teams",
      position: { lateralYards: 4, depthYards: 0 },
      symbol: "triangle",
      label: "T",
      sublabel: "triangle",
      fill: "half",
      color: "orange",
    },
    {
      id: "player-x",
      unit: "defense",
      position: { lateralYards: 12, depthYards: 0 },
      symbol: "x",
      label: "",
      sublabel: "x",
      fill: "none",
      color: "red",
    },
    {
      id: "player-letter",
      unit: "defense",
      position: { lateralYards: 20, depthYards: 0 },
      symbol: "none",
      label: "M",
      sublabel: "letter",
      fill: "none",
      color: "gray",
      role: "middle-linebacker",
      group: "linebackers",
    },
  ],
  paths: [
    {
      id: "binding-path",
      kind: "route",
      playerId: "player-circle",
      points: [
        { lateralYards: -20, depthYards: 0 },
        {
          lateralYards: -12,
          depthYards: 10,
          control: { lateralYards: -20, depthYards: 8 },
        },
      ],
      branches: [],
      style: { line: "solid", ending: "arrow", color: "ink" },
    },
  ],
  labels: [
    {
      id: "label-landmark",
      position: { lateralYards: -20, depthYards: 15 },
      text: "12 Yds",
      color: "gray",
      size: 11,
      box: "none",
      boxColor: "yellow",
      mono: true,
      role: "landmark",
    },
    {
      id: "label-assignment",
      position: { lateralYards: -12, depthYards: 15 },
      text: "settle",
      color: "ink",
      size: 11,
      box: "none",
      boxColor: "yellow",
      caps: true,
      mono: true,
      role: "assignment",
    },
    {
      id: "label-progression",
      position: { lateralYards: -4, depthYards: 15 },
      text: "1",
      color: "blue",
      size: 12,
      box: "circle",
      boxColor: "blue",
      role: "progression",
    },
    {
      id: "label-adjustment",
      position: { lateralYards: 4, depthYards: 15 },
      text: "max split +4",
      color: "ink",
      size: 11,
      box: "fill",
      boxColor: "yellow",
      caps: true,
      role: "adjustment",
    },
    {
      id: "label-alert",
      position: { lateralYards: 12, depthYards: 15 },
      text: "yes / no",
      color: "red",
      size: 12,
      box: "outline",
      boxColor: "red",
      caps: true,
      role: "alert",
      leader: {
        endpoint: { lateralYards: 14, depthYards: 10 },
        line: "dashed",
      },
    },
    {
      id: "label-coaching",
      position: { lateralYards: 0, depthYards: 0 },
      text: "Eyes first",
      color: "ink",
      size: 11,
      box: "outline",
      boxColor: "ink",
      role: "coaching",
      leader: {
        endpoint: { lateralYards: -13, depthYards: 8 },
        line: "solid",
      },
      binding: {
        pathId: "binding-path",
        segmentIndex: 1,
        progress: 0.5,
        offset: { lateralYards: 2, depthYards: 0.5 },
      },
    },
  ],
} satisfies PlayDocument;

export const playerLabelPrimitivePlay = playDocumentSchema.parse(fixture);
